### ISSUE TITLE
Python package dependency question

### ISSUE THREAD

**Issue by crbinz** [JuliaCI/PackageEvaluator.jl#117]
[SGP4.jl](https://github.com/crbinz/SGP4.jl) requires the python `sgp4` package to be installed. I've always used `pip install sgp4` without issue.

I notice the README says that dependencies like this should be added to `scripts/setup.sh`, but I also notice that there are no other `pip install ...` lines in the file currently, which makes me think there may be a different approach I'm not seeing. Could someone clarify what I should do here? Thanks in advance.

**Comment by IainNZ** [comment]
Hi @crbinz. Until very recently there were some `pip install`s, but it turns out all of them were able to use Conda.jl (https://github.com/IainNZ/PackageEvaluator.jl/pull/105), by @dhoegh. Maybe such a thing could be done for your package as well?

**Comment by crbinz** [comment]
I will look into it, thanks for the tip.

**Comment by dhoegh** [comment]
It seems that sgp4 is not in the Conda package enviroment. @luthaf Should we add a `add_pip` function to Conda.jl to manage the packages on pip which is not in the Conda package enviroment?

**Comment by Luthaf** [comment]
> Should we add a add_pip function to Conda.jl to manage the packages on pip which is not in the Conda package enviroment?

I do no understand what you mean here. Do you want to use pip with the Conda-provided Python installation, or with the system-wide one ?

I strongly disagree with the second alternative, and the first one could be achieved by running `run($(joinpath(Conda.BINPATH, "pip")) install ...`, and using `Conda.add("pip")` as needed.

**Comment by dhoegh** [comment]
I thought of providing a `pip_add` function in Conda.jl, to enable people to install packages from pip without touching the Conda.jl internals. The function could look as:
```
function pip_add(pkg)
    if haskey(_installed_packages_dict(), "pip")
        run(`$(joinpath(Conda.BINPATH, "pip")) install $pkg`
    end
end
```

**Comment by Luthaf** [comment]
> to enable people to install packages from pip without touching the Conda.jl internals

People using Conda.jl should be package developers, so we can ask them to dig a bit in the Conda internals for that =) I usually prefer to do only one thing from a library, and let the users of the library build on the top of it.

**Comment by crbinz** [comment]
>``run(`$(joinpath(Conda.BINDIR, "pip")) install sgp4`)``

Is this the way to go for this particular issue?

**Comment by Luthaf** [comment]
If you want to use Conda to manage your Python and sgp4 dependency, yes. You also should use `Conda.add("pip")` to install Python and `pip` on the users machines.

You could also use PyCall to install the pip module and use the system-wide Python. This would select any pre-installed Python installation on the user machine, and would not download another full Python installation. 

And finally, as sgp4 seems to be C++ code, you could create [conda recipes](http://conda.pydata.org/docs/building/recipe.html) for it, and upload the build on binstar. This would remove the dependency on Python altogether.

**Comment by crbinz** [comment]
I don't think there's any outstanding issue here, closing.
