### ISSUE TITLE
XMLDict.jl tests

### ISSUE THREAD

**Issue by samoconnor** [JuliaCI/PackageEvaluator.jl#118]
Tests pass on Travis: 

https://travis-ci.org/samoconnor/XMLDict.jl

But fail on PackageEvaluator.jl:

http://pkg.julialang.org/detail/XMLDict.html

`bash: xmllint: command not found `

Any chance of having `xmllint` installed on the test vm? It seems like Travis has it by default.

**Comment by IainNZ** [comment]
It seems like you install it, per your Travis:
```
packages:
      - libxml2-utils
```

Is `xmllint` only needed for testing? If so, I think it'd be OK to add it to the VM - please submit a PR.

**Comment by samoconnor** [comment]
> seems like you install it
Ah, true. I'd forgotten that.

Yes, xmllint is only needed for testing.

**Comment by IainNZ** [comment]
Bump for the PR

**Comment by samoconnor** [comment]
Hi @IainNZ,

I'm afraid this is fairly far down my priority list just at the moment.
I've just been through a pass of cleaning up my local collection of hacks and pushing useful stuff upstream. But I'm now back to an intense period of work for clients. At this point I can't justify the overhead of downloading/building/learning `PackageEvaluator.jl` enough to submit a PR.

Perhaps you could parse the travis `packages:` list and automatically deploy them to the `PackageEvaluator.jl` VM as well.
