### ISSUE TITLE
Having a semi-stable snapshot of all packages

### ISSUE THREAD

**Issue by maximsch2** [JuliaCI/PackageEvaluator.jl#121]
I was wondering if you are interested in pushing PackageEvaluator a bit further: right now a lot of packages are not tagging new versions that often, and so PkgEval is not testing them. This makes it attractive to live on the master branch through `Pkg.checkout` up until the point something breaks in there. 

It would be really cool if we would have a separate METADATA.jl package, say METADATA-next.jl which would be automatically populated by PkgEval once the package passes all unit tests (maybe including unit tests of dependants for some core libraries). 

This way, people interested in using latest version of packages can live on METADATA-next, while still enjoying some stability. And if something is broken, then those people are presumably interested enough to submit a PR to add a test. Adding a broken test would be detected by PkgEval and package will be downgraded to the latest version that was working (those tests might have to live in some separate repository for this to work, which is an additional advantage as some of the PRs take a really long time to get accepted to some packages).

Does it make sense? Do you think it will be feasible with current PkgEval infrastructure (it will most likely require more computational resources for backtracking to find last working package version)?

**Comment by IainNZ** [comment]
Hi @maximsch2. I think this could maybe be done computationally-speaking if you picked one version of Julia (e.g., 0.4), but I won't ever have the time for evaluating this proposal. I suggest you take the code/inspiration here and run with it though - perhaps a prototype run, see if people like the results, and go from there. You'll need to modify PkgEval, but really if you look at the code there isn't that much going on, its just a lot of setup and teardown and nothing conceptually complicated.

For what its worth, I don't think there will be much appetite for this. As a maintainer on some large/popular projects like JuMP.jl, while we keep master passing tests that doesn't mean the package is in a senseable state between releases, and things are subject to change all the time in that time between releases. But, its open source, so maybe try it and see what happens.

**Comment by maximsch2** [comment]
Hm, it's an interesting point about JuMP.jl. I was playing with packages in different direction (Stats/ML as well as Escher.jl and all it's web-related dependencies) and I had to live on master branch for a bunch of them either because some functionality is broken or the release is so old that it is cluttering the output with deprecation warnings for 0.4 (e.g. see https://github.com/JunoLab/Hiccup.jl/issues/8, https://github.com/JuliaWeb/HttpServer.jl/issues/80, https://github.com/JuliaWeb/WebSockets.jl/issues/50, https://github.com/dirkschumacher/PValueAdjust.jl/issues/7, https://github.com/lindahua/EmpiricalRisks.jl/issues/15 just for missing tag for 0.4 release). 
Is there a way to download all PkgEval logs in a batch to see how often do packages still produce those warnings?

**Comment by IainNZ** [comment]
https://github.com/IainNZ/pkg.julialang.org/tree/gh-pages/logs

I'd be interested in seeing that analysis, and/or adding a feature to the scripts that generate the site that show if there are deprecation warnings. In fact, on thing on my probably-never-gonna-get-to-do list is going back to four status: passes, passes with deprecation warnings, fails, no tests, NA.

**Comment by maximsch2** [comment]
A really quick analysis shows that 24% of 0.4 logs and 41% of 0.5 logs contain the word "deprecated" and 35%/60% correspondingly contain the word "WARNING". These numbers are obviously inflated for cases when a package that is used by a bunch of others produces warnings, I'll see if I will be able to untangle those.
An interesting question now along the lines of what I was suggesting here would be to look at logs like this for master branches of all the packages and see if the number of the deprecation warnings is significantly smaller (e.g. they are fixed and people have just forgotten to tag new versions).
