### ISSUE TITLE
Too old cmake and gcc

### ISSUE THREAD

**Issue by barche** [JuliaCI/PackageEvaluator.jl#123]
Hi,

CxxWrap is currently failing because CMake and presumably GCC is too old. On Travis, I need to install extra packages like this:
https://github.com/barche/CxxWrap.jl/blob/master/.travis.yml

Is there a way to translate this to PackageEvaluator? Would it be harmful to just put CC and CXX to use gcc4.9 always?

**Comment by tkelman** [comment]
The VM starts from stock Ubuntu 14.04. Is that really too old?

**Comment by ufechner7** [comment]
I am using Ubuntu 14.04, and gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
is working fine. But for CMake a newer version is needed. Is it possible to install a newer version of CMake just for this package/ test?

**Comment by ufechner7** [comment]
I am using cmake version 3.2.2, and I installed it using the following ppa:
``
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:george-edison55/cmake-3.x
sudo apt-get update
sudo apt-get install cmake
``

**Comment by tkelman** [comment]
You can't relax the cmake requirement? What do you need that isn't available in the default ubuntu 14.04 package?

**Comment by barche** [comment]
The only CMake 3 feature used seems to be the export command, which is only needed when building an external project against the build directory. That scenario doesn't seem very likely in the case of CxxWrap, since installation is done to deps/usr anyway, so I suppose I could adapt to CMake 2.8.12.

Regarding GCC, I got confused, I thought this was the same as Travis but that's Ubuntu 12.04. GCC 4.8 is fine.

**Comment by ufechner7** [comment]
It would be nice, if you could check if CxxWrap also works with CMake 2.8.x . This would make the installation for people, who are using Ubuntu 14.04 easier.

**Comment by barche** [comment]
Yes, I will adapt it, so I think this issue can be closed.
