### ISSUE TITLE
clarification of the relation of PackageEvaluator and pkg.julialang.org?

### ISSUE THREAD

**Issue by lobingera** [JuliaCI/PackageEvaluator.jl#124]
The Readme.md starts with the sentence

> The purpose of PackageEvaluator is to attempt to test every Julia package nightly, and to provide the information required to generate the Julia package listing.

Is there plan to make this daily, or will it stay in the order-of-weeks-update (i'm not complaining about the cycle, it's just unclear to me).

**Comment by IainNZ** [comment]
It was daily, it would ideally be daily, there has just been a lack of time to make it work reliably daily, primarily due to some strange issues on 0.5

**Comment by lobingera** [comment]
I see. Thanks for the quick answer.
