### ISSUE TITLE
Add new state for "passes with deprecation warnings"?

### ISSUE THREAD

**Issue by IainNZ** [JuliaCI/PackageEvaluator.jl#129]
Worth it? I was prompted about this again after seeing some quite old packages that show up as green but I suspect a maybe not up-to-date and just have a very simple test.

**Comment by tkelman** [comment]
Yes it's a good idea, though possibly hard to distinguish between
- package itself has deprecation warnings
- package and/or any of its dependencies have deprecation warnings

**Comment by IainNZ** [comment]
So hard as to be impossible, but, OTOH, we don't attempt to distinguish why exactly a package is failing, and I'm not sure end users appreciate the distinction much anyway (if they even should care).

Related to that: I've always wanted to draw the package dependency tree with coloured boxes depending on test status...

**Comment by TotalVerb** [comment]
I think it's helpful for packages to be invested in their dependencies' deprecation warnings. Deprecation warnings make things slow and an overall poor user experience. More pressure/hands to fix them quickly should help things.

**Comment by IainNZ** [comment]
Seems a bit more complex than anyone has appetite to handle, so closing for now.
