### ISSUE TITLE
Strange failure for Currencies.jl

### ISSUE THREAD

**Issue by TotalVerb** [JuliaCI/PackageEvaluator.jl#133]
Currencies.jl is [failing tests](http://pkg.julialang.org/logs/Currencies_0.5.log) on pkg.julialang.org. I looked into the logs, and the relevant part seems to be:

    ERROR: LoadError: __precompile__(false) is not allowed in files that are being precompiled
     in __precompile__(::Bool) at ./loading.jl:272
     in include_from_node1(::String) at ./loading.jl:426
     in macro expansion; at ./none:2 [inlined]
     in anonymous at ./<missing>:?
     in eval(::Module, ::Any) at ./boot.jl:231
     in process_options(::Base.JLOptions) at ./client.jl:243
     in _start() at ./client.jl:322
    while loading /home/vagrant/.julia/v0.5/GnuTLS/src/GnuTLS.jl, in expression starting on line 1

This error, as far as I can tell, is in GnuTLS, not Currencies. But no package depends on GnuTLS:

    julia> length(Pkg.dependents("GnuTLS"))
    0

How can an error in the package that Currencies.jl is not depending on cause Currencies.jl to fail tests? The tests pass locally, and Requests.jl's (Currencies.jl's only dependency) tests pass, so I think this might be a PackageEvaluator issue.

The only thing I can think of is that Currencies.jl moved from TotalVerb/ to JuliaFinance/. But I don't understand how this involves GnuTLS.

**Comment by tkelman** [comment]
fixed by https://github.com/JuliaLang/METADATA.jl/issues/5415 - for some reason using Requests 0.0.1 which didn't have a JSON dependency was preferred over downgrading JSON.

**Comment by TotalVerb** [comment]
Looks to me like I need a version requirement!

**Comment by tkelman** [comment]
that wouldn't hurt either
