### ISSUE TITLE
3 issues with specific packages

### ISSUE THREAD

**Issue by sbromberger** [JuliaCI/PackageEvaluator.jl#137]
Hi,

1) Both LightGraphs.jl and LightGraphsExtras.jl packages have the same BSD 2-clause license, but pkg shows LightGraphs having an MIT license, and LGE having a 3-clause BSD license. How do I get this fixed?

2) Pkg shows LightGraphsExtras as being "deprecated" - this couldn't be farther from the truth. What's causing this?

3) How often are the dependency counts updated? Pkg is showing 39 dependencies for LGE and 38 for LG - LG should be way down now that we've pruned the heavy dependencies out into LGE.

**Comment by tkelman** [comment]
1. Licenses get detected [here](https://github.com/JuliaCI/PackageEvaluator.jl/blob/master/src/prepjson.jl#L15-L25) based on [these regexes](https://github.com/JuliaCI/PackageEvaluator.jl/blob/90cc3da93e2a670ba86377a46ca6f300ea24d913/src/constants.jl#L15-L48). I think the fact that MIT gets checked first, and you have the includes-codes-from-Graphs.jl "permission is hereby granted, free of charge," later on in the file means it's matching MIT first. We could make the license detection smarter by trying to match on all the regexes and returning the license that has a match earliest in the file or something? PR's welcome.

2. Whether or not a package is listed as deprecated is determined [here](https://github.com/JuliaCI/PackageEvaluator.jl/blob/90cc3da93e2a670ba86377a46ca6f300ea24d913/website/build_site_data.jl#L34-L42), so all of the work is done by MetadataTools.jl [in these functions](https://github.com/IainNZ/MetadataTools.jl/blob/v0.3.2/src/MetadataTools.jl#L60-L168). Basically if every tagged version of the package has a `julia` upper bound, `build_site_data.jl` considers it "deprecated." That's not exactly accurate for packages like yours where you're being conservative about the future versions of Julia that you claim to support now. Upper-bounding Julia is preventing people on the 0.5 release candidates from easily installing these packages with `Pkg.add`, so it might be better not to apply bounds unless you're absolutely positive it doesn't work at all (and have a version tagged that works better). We could rephrase this in generating the site, pick a more precise term and maybe even include the max supported version of Julia.

3. PackageEvaluator runs nightly on a cron job at 12:20 am eastern, and if everything runs correctly then the website gets updated when it's finished, roughly 10 hours later.

**Comment by sbromberger** [comment]
Thanks for the detailed explanation. We will eventually be cutting over to 0.5 support for LGE.

Could I suggest that you reconsider removing the "deprecated" tag if the upper bound includes the current stable release?

**Comment by tkelman** [comment]
If you'd like to make the necessary code change in a PR I'll review it.
