### ISSUE TITLE
DifferentialEquations Tests Fail: FileIO not found in current path

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaCI/PackageEvaluator.jl#138]
You can see from the [test log](http://pkg.julialang.org/logs/DifferentialEquations_0.4.log)

``` julia
ERROR: LoadError: module FileIO not found in current path; you should rm("/home/vagrant/.julia/lib/v0.4/FileIO.ji") to remove the orphaned cache file
 in error at ./error.jl:21
 in recompile_stale at loading.jl:472
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:235
 in stale_cachefile at loading.jl:457
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:235
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/DifferentialEquations/src/DifferentialEquations.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile DifferentialEquations to /home/vagrant/.julia/lib/v0.4/DifferentialEquations.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:266
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/DifferentialEquations/test/runtests.jl, in expression starting on line 8
```

I'm not quite sure what it could be because the tests pass locally, on Travis, and on AppVoyer. I had similar issues with FileIO before, but only when I had a test that included JLD functionality (and only on Travis). I disabled the test and haven't had that dependency for awhile, but the tests still fail because of FileIO.

**Comment by tkelman** [comment]
I believe what this means is one of the packages that comes before you on the same VM (runs alphabetical) is doing something fishy or wrong with precompilation and/or optional dependencies.

**Comment by ChrisRackauckas** [comment]
Is there anything I can do about it? Can I add the remove statement, or have only the VM add FileIO?

**Comment by tkelman** [comment]
Your package shouldn't be removing cache files. It would be worth finding which package preceding yours in the same VM did something strange. The sequence of events that pkgeval runs are something that you could do anywhere, so some package is doing something buggy.

**Comment by ChrisRackauckas** [comment]
The FileIO error on v0.5 magically went away. Not v0.4 though.

**Comment by tkelman** [comment]
Let me know if you ever see this kind of thing in pkgeval results from 0.5.2 or later. I think this should be fixed, where cache files will now be marked stale if anything they depend on is no longer installed.

**Comment by ChrisRackauckas** [comment]
Thanks!
