### ISSUE TITLE
MySQL required for some packages

### ISSUE THREAD

**Issue by mirestrepo** [JuliaCI/PackageEvaluator.jl#139]
MySQL (@nkottary) and BioMedQuery require a mysql server installed in the remote for tests to pass

I'm not fully sure what's the best way to do so. I think it will require adding to setup.sh
`sudo apt-get install mysql-server to setup.sh`
This will however will prompt to set up the root password. Travis accepts empty passwords for root so perhaps that's okay to do. Additionally the server will need to get started. Is setup.sh also the place to do so?

Any ideas?

**Comment by tkelman** [comment]
For things that are runtime dependencies, I usually advise the package to try to handle installation. How are users expected to get up and running with the packages, especially on Windows or Mac? PackageEvaluator tests only Linux at the moment and does have a set of things that it sets up with apt-get during VM provisioning, but that doesn't help your average user who does `Pkg.add` and might not have dependencies installed yet. Or what if someone wants to use the package but doesn't have root?

**Comment by mirestrepo** [comment]
You are right, these packages expect a mysql server installed and running. 

We could provide setup scripts (or something similar to the .travis config scripts) to install mysql using apt-get or home-brew in the cases of linux and mac, but that still won't solve it for non-root users. And I'm not sure what the best way to do it in windows would be. 

But is there a way to call the config scripts automatically when Pkg.add is called?

**Comment by tkelman** [comment]
Yeah, you add a script at `deps/build.jl`. many packages leverage BinDeps.jl for this. How hard is mysql to compile from source if you're not root?

**Comment by mirestrepo** [comment]
I haven't tried it, but I assume with cmake things should go relatively smooth. I'll look into it and into BinDeps.jl

**Comment by tkelman** [comment]
best bet is to look at an example. should probably be implemented in MySQL.jl, then BioMedQuery just depends on it right? MbedTLS.jl is a pretty good example of BinDeps usage. Or Nettle.jl, or ECOS.jl are also worth checking.

**Comment by nkottary** [comment]
`mysql-client` would need to be installed through `deps/build.jl` and the PATH to the client set.

`test/runtests.jl` in MySQL.jl could be modified to pick up server config from a conf file which you can edit in your shell script which can also install `mysql-server`.

**Comment by mirestrepo** [comment]
@nkottary would you be willing to apply these changes to MySQL.jl?

**Comment by nkottary** [comment]
I have the following pull requests open for this
* [#61](https://github.com/JuliaDB/MySQL.jl/pull/61)
* [#62](https://github.com/JuliaDB/MySQL.jl/pull/62)

**Comment by IainNZ** [comment]
Closing due to lack of action.
