### ISSUE TITLE
ArbFloats fails, but I don't think it should

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaCI/PackageEvaluator.jl#149]
If ArbFloats is installed properly, and that requires pre-installing Nemo (which is not required because REQUIREing Nemo rebuilds it whenever ArbFloats is rebuild and Nemo takes a long time to build) . Instead, if Nemo is not present a message is issued with an instruction to add it.
with Nemo present, Pkg.test("ArbFloats") works.

How can the package ecosystem listing reflect this state of affairs?

**Comment by tkelman** [comment]
Dependencies belong in REQUIRE.

**Comment by JeffreySarnoff** [comment]
Done, Thank you
