### ISSUE TITLE
Is PackageEvaluator working?

### ISSUE THREAD

**Issue by tlnagy** [JuliaCI/PackageEvaluator.jl#153]
I've recently tagged new versions of Gadfly and Compose, but PackageEvaluator appears to been down for ~ 1 month?

http://pkg.julialang.org/detail/Gadfly.html

**Comment by tkelman** [comment]
It's freezing on nightly. Some of the deprecations are repeating infinitely causing several packages to just hang. https://github.com/JuliaLang/julia/issues/20220 is related.

**Comment by tlnagy** [comment]
But it looks like it's been hanging on 0.4 and 0.5 too?

**Comment by tkelman** [comment]
No, those run to completion but results don't get uploaded unless all runs finish.

**Comment by tlnagy** [comment]
Ah. That makes sense.

**Comment by tlnagy** [comment]
Hey @tkelman, it looks like Gadfly tests are failing on 0.5 again (http://pkg.julialang.org/logs/Gadfly_0.5.log). it looks like Fontconfig isn't installed properly? Is that something specific to PackageEvaluator or?

**Comment by tkelman** [comment]
see https://github.com/JuliaCI/PackageEvaluator.jl/issues/146

it's a byproduct of fragile approximations of conditional dependencies interacting badly with precompilation. make all dependencies unconditional, or move optional code to separate packages that unconditionally depends on everything it uses, and this will stop happening.
