### ISSUE TITLE
Visual regression tests failing on pkg.julialanguage.org

### ISSUE THREAD

**Issue by juliohm** [JuliaCI/PackageEvaluator.jl#161]
All visual tests pass locally on my laptop and on Travis CI:

https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/219012650

but fail on pkg.julialanguage.org:

http://pkg.julialang.org/logs/ImageQuilting_0.5.log

Could you please help me debug what is causing this failure? I rebuilt on Travis multiple times and everything is working there.

**Comment by juliohm** [comment]
Is there a way to test changes locally before tagging a new version?

**Comment by tkelman** [comment]
You can run PkgEval locally on a test branch of metadata, but it takes quite some time and a beefy machine to get through the whole thing

**Comment by juliohm** [comment]
Thank you @tkelman , I think I will skip it then, wait for the next tag that should come with Julia v0.6 anyways.
