### ISSUE TITLE
Plots listed as "untestable"

### ISSUE THREAD

**Issue by mkborregaard** [JuliaCI/PackageEvaluator.jl#164]
We've got the Plots tests machinery working again, so I don't believe it should be listed as "untestable" anymore.

**Comment by tkelman** [comment]
could be removed from https://github.com/JuliaCI/PackageEvaluator.jl/blob/2ab61989aa9d75c06da8e4ac8dc46f2736c37e0b/src/constants.jl#L137 then and see what happens

**Comment by mkborregaard** [comment]
Are you suggesting I do a PR removing it?

**Comment by mkborregaard** [comment]
Ah, I see you are, Tom added https://github.com/JuliaCI/PackageEvaluator.jl/pull/125 . OK, I will do that, will take me a little while to do it (it needs some setup on PlotReferenceImages too I can see)

**Comment by tkelman** [comment]
I could also just take it out if that's what you're sure you want to do. If you have vagrant I can tell you what to hack up locally to do a pkgeval run that actually only runs Plots' tests

**Comment by mkborregaard** [comment]
Yes, that'd be cool. 

If it's OK I'd like to wait with doing it, as I will be away from keyboard from the beginning of the week until August (I will in fact not have internet access), so I am afraid of starting anything that might blow up now. (We'd need to have a system with dedicated release branches on our PlotReferenceImages repo which is used to store the images for the tests, as that changes frequently - also, all our tests fail once matplotlib or GR push a new version that change visuals so there'd be intermittent spurious failures).

I will revisit this once I get back and experiment with it.

**Comment by tkelman** [comment]
I think what it'll need, other than the change to that list, is locally modifying https://github.com/JuliaCI/PackageEvaluator.jl/blob/2ab61989aa9d75c06da8e4ac8dc46f2736c37e0b/scripts/setup.sh#L141-L147 to say something more like
```
if [ "$2" == "all" ]
then
    LOOPOVER=/home/vagrant/.julia/v${1}/METADATA/Plots
elif [ "$2" == "AK" ]
then
    LOOPOVER=/home/vagrant/.julia/v${1}/METADATA/Plots;
elif [ "$2" == "LZ" ]
then
    LOOPOVER=/home/vagrant/.julia/v${1}/METADATA/Plots;
fi
```
though I haven't tested this myself yet. The normal way to run pkgeval is by running the `./runvagrant.sh` script in `setup`. By default it splits across 6 VM's running simultaneously, across 3 different versions of Julia and splitting the package list in half. The initial provisioning of installing all the various apt-get packages before starting the Julia package testing can take tens of minutes, you can tail the `half*.out.txt` files to see how far they've gotten.

**Comment by mkborregaard** [comment]
Thanks, I'll check this out.

**Comment by mkborregaard** [comment]
Why was this closed? Plots is still listed as "untestable", though it tests with no problem in our own CI workflow.

**Comment by IainNZ** [comment]
Then file a pull request to make it testable if you are a maintainer of Plots.jl.
