### ISSUE TITLE
BeaData fails because API key needed

### ISSUE THREAD

**Issue by stephenbnicar** [JuliaCI/PackageEvaluator.jl#166]
Initializing a connection to the BEA Web API requires an individual key.  I get around the issue on Travis by providing an encrypted key for the environment, but I'm don't know if something comparable is available for PackageEvaluator.

**Comment by tkelman** [comment]
We can put some file in the home directory, but I don't see an easy way of doing that without making it public in the code here.

**Comment by stephenbnicar** [comment]
So would it be best just to submit a PR for src/constants.jl with BREAKS?
