### ISSUE TITLE
What is history path for `build_site_data.jl`?

### ISSUE THREAD

**Issue by ulysses4ever** [JuliaCI/PackageEvaluator.jl#168]
I'm trying to get PkgEval working on my local machine. I'm following `README` instructions: I ran vagrant to get one huge json file (0.6all.json), then I ran `src/pull_repo_info.jl` to get JLD-file, then I ran `src/build_site_data.jl`. The latter fails with:

> "Expected 3 arguments: log folder, badge folder, history path"

First to args, I guess, just empty dirs to store some data. But the last one is (given comments on the source code) is some CSV-database with some history. Where should I get one?

**Comment by tkelman** [comment]
See https://github.com/JuliaCI/PackageEvaluator.jl/blob/master/website/build.sh and https://github.com/JuliaCI/PackageEvaluator.jl/blob/master/scripts/cronjob.jl

**Comment by ulysses4ever** [comment]
@tkelman thanks for the reply! 

`build.sh` requires the same data (it has the names for csv-files hardcoded though) -- so it does not really help. 

`cronjob.jl` -- I don't fully understand it and it has a lot of hardcoded stuff -- so I'm not sure how to use it. Does it build csv-data for `build_site_data.jl`?

**Comment by tkelman** [comment]
the csv files come from the repo https://github.com/JuliaCI/pkg.julialang.org
