### ISSUE TITLE
Environment variable to identify runs on Julia servers?

### ISSUE THREAD

**Issue by juliohm** [JuliaCI/PackageEvaluator.jl#170]
I am currently skipping some of the tests on Travis because of the instability and constant changes in Plots.jl. I can do it because Travis CI defines the environment variable `TRAVIS`: https://github.com/juliohm/ImageQuilting.jl/blob/master/test/runtests.jl#L7

Is there an equivalent variable to check when we submit a new tag to julialang? My tests are passing locally but visual regression tests fail with different versions of Plots.jl in the server apparently.

I want to skip visual regression tests when I submit a new tag.

**Comment by juliohm** [comment]
Could you please help with this issue? Everything is working perfectly fine in my package, however the red badges on the README can scare people from trying the code.

**Comment by tkelman** [comment]
Could you raise the tolerance a bit for the one that doesn't match? It's pretty standard Ubuntu 14.04 so users could easily hit the same difference.

**Comment by juliohm** [comment]
@tkelman the tolerance is not the issue. The reason why the visual test is failing is purely due to the constant changes in Plots.jl. Sometimes the whitespace is changed in the axes, sometimes the label size changes, all of this doesn't contribute to the nature of the test. If I change the tolerance today, it may fail tomorrow again.

As you can see here https://github.com/juliohm/ImageQuilting.jl/blob/master/test/runtests.jl#L122 I am still performing visual regression tests on Travis Linux because this is the closest environment to my machine and because I have the flexibility to update the reference images and push again to fix the red badge. When I submit a tag to METADATA, if the test fails, I cannot fix the badge.

Having an environment variable or a way to check that I am on `PackageEvaluator.jl` would be extremely helpful.

**Comment by tkelman** [comment]
changes in upstream packages making tests fail is exactly what pkgeval is supposed to find

**Comment by juliohm** [comment]
The problem here is more subtle though, there is no issue with ImageQuilting.jl, but if at some point the layout of a plot in Plots.jl changes, the image generated will be (let's say) shifted to the right by a few pixels and the distance calculated will pass the threshold in the tests. In that sense, I find myself without control in making my users feel safe. They will always see a red badge on my package and I am currently unable to fix this.

**Comment by juliohm** [comment]
Hi @tkelman, as you can see I got the red badge again in PackageEvaluator.jl even though the tests pass on Travis CI:

https://pkg.julialang.org/logs/ImageQuilting_0.6.log

**Comment by tkelman** [comment]
Does the `InitError(:Gtk, ErrorException("Cannot open display: "))` have anything to do with that? Might need to set the xvfb-run flag if it's trying to display something.

**Comment by juliohm** [comment]
This is from VisualRegressionTests.jl, it is just a warning, shouldn't
affect the results.

**Comment by tkelman** [comment]
Then what's the difference between what's running on Travis vs pkgeval? If you set `dist: trusty` on Travis would it fail there too?

**Comment by juliohm** [comment]
I think `VisualRegressionTests.jl` with `Plots.jl` is a relatively unstable method. I am considering running these tests on my laptop only. I will knock out the visual regression tests from the bots. At the end of the day, I am the only person merging pull requests anyways.

**Comment by juliohm** [comment]
Hi @tkelman , can I safely assume that the variable TRAVIS is not defined in the PackageEvalutor.jl build?

I am planning to only test on my local laptop and on TRAVIS CI Linux.

**Comment by juliohm** [comment]
If PackageEvaluator.jl doesn't define TRAVIS, I can run the visual tests not only on my laptop, but on the Travis CI servers. Please let me know if that is the case. Also, feel free to close this issue anytime, the badge is finally green again :blush:

**Comment by tkelman** [comment]
It does not define the TRAVIS env var, no.

**Comment by juliohm** [comment]
Awesome, I will update the tests accordingly, closing this. Thank you.
