### ISSUE TITLE
on-demand retests for pkg.julialang.org?

### ISSUE THREAD

**Issue by sbromberger** [JuliaCI/PackageEvaluator.jl#171]
This is probably a tall order, but it'd be nice to be able to selectively retest apps that come up as "failing" - in our latest case, it's the result of a random graph generator not quite making the cut. It happens occasionally, but we don't really want to relax the testing standard.

**Comment by tkelman** [comment]
Your tests being flaky is a bug in the package.

**Comment by sbromberger** [comment]
Probably, but it's a bit difficult to bound randomness. It happens occasionally but not frequently enough to cause a big problem. We'll take another look, though.

**Comment by tkelman** [comment]
No, it isn't doable right now to re-trigger a single package. It re-runs daily. PkgEval will likely be replaced by something that can run on demand in a more targeted fashion, but no ETA on that. It would use a similar backend to what the JuliaCIBot was doing on metadata, but that's been out of commission for a week or two.
