### ISSUE TITLE
Build error on MacOS

### ISSUE THREAD

**Issue by juliohm** [JuliaCI/PackageEvaluator.jl#173]
https://travis-ci.org/juliohm/GeoStats.jl/jobs/262777096

I tried restarting the build and the error persists.

**Comment by tkelman** [comment]
That was a download failure, and has nothing to do with PackageEvaluator

**Comment by juliohm** [comment]
Hi @tkelman , the error doesn't seem to be a download failure now: https://travis-ci.org/juliohm/GeoStats.jl/jobs/262880640 it is something to do with GKS maybe?

**Comment by juliohm** [comment]
Probably a change in the GTK package or VisualRegressionTests.jl
