### ISSUE TITLE
Julia v0.5 Dropped on PowerModels.jl?

### ISSUE THREAD

**Issue by ccoffrin** [JuliaCI/PackageEvaluator.jl#175]
Something strange seems to be going on with the latest evaluation of [PowerModels.jl](https://pkg.julialang.org/detail/PowerModels.html).  

1) the Julia v0.5 seems to be missing?
2) the Julia v0.6 package eval build is failing, but I cannot reproduce on [travis](https://travis-ci.org/lanl-ansi/PowerModels.jl/builds/268751025).

Any insights would be much appreciated.

**Comment by ararslan** [comment]
PackageEvaluator no longer runs tests on 0.5. Looks like 0.6 is fine now for PowerModels.
