### ISSUE TITLE
Outdated package list?

### ISSUE THREAD

**Issue by Azzaare** [JuliaCI/PackageEvaluator.jl#176]
Following a discussion on the Julia Discourse, it seems the list of packages is not up to date (whatever the reason is).

For instance, [PGFPlotsX](https://github.com/KristofferC/PGFPlotsX.jl) is registered since long, but it doesn't appear in the current list.
Also, it seems some packages do not appear as tested with version v0.6 as they are supposed to be.
Is there a specific reason?

On a side note, the current update date of the package list is "2017-10-01". Is it October 1st or January 10th Maybe printing "2017-Oct-01" can avoid confusion.

**Comment by sambitdash** [comment]
@Azzaare normally when yyyy comes in first the date format is: "yyyy-mm-dd". Hence, many 

The package list is broken. I see PDFIO, LabelNumerals are no longer in the list. While AdobeGlyphList which was registered later is in the list.

**Comment by ararslan** [comment]
The dates are represented in ISO 8601 format, i.e. yyyy-mm-dd, as Sambit noted above. This is standard and I doubt we'll change it.

Regarding the package listing, the website hasn't been updated correctly in quite a while, and I'm actively looking into that. See also #179.

Closing in favor of #179, plus "won't fix" for the date format.
