### ISSUE TITLE
Tests aren't being run anymore for some packages?

### ISSUE THREAD

**Issue by tlnagy** [JuliaCI/PackageEvaluator.jl#179]
It looks like the PackageEvaluator tests aren't being run any more? E.g. https://pkg.julialang.org/detail/OMETIFF hasn't been run since September and I've pushed two new releases to Metadata.jl since then. The build log is from back then too. I can't see any sign of the tests running and then failing.

**Comment by ararslan** [comment]
PackageEvaluator has been running the package tests but hasn't successfully updated the website in quite a while. I'm still trying to figure out why that is but I'm actively investigating. I'll let you know what I find out.

**Comment by tlnagy** [comment]
@ararslan @tkelman Any update on this? Looks like the website hasn't been updated since October 1st?

**Comment by ararslan** [comment]
I've been busy with other things and haven't had time to continue my investigation. I'll see if I can get to it in the next few days.

**Comment by ararslan** [comment]
I got a run to go through manually and I have a PR up to fix the issues (#181). Things need to be updated to drop 0.4 and add 0.7 (#178), after which I'll set up the cron job again.

**Comment by ararslan** [comment]
Things should be in order now. Let me know if you run into any more issues.

**Comment by bjarthur** [comment]
gadfly 0.7 was released 22 days ago and PkgEval hasn't been updated for it, despite other packages saying they were updated 5 days ago.

might this be related to filing a [joint PR](https://github.com/JuliaLang/METADATA.jl/pull/14746) to METADATA for both Gadfly and Compose?

**Comment by ararslan** [comment]
Not likely.

**Comment by bjarthur** [comment]
ok, what then?  how do we get it in the queue?

**Comment by ararslan** [comment]
It's just a guess. I'm not sure; I don't actively maintain PackageEvaluator anymore.

**Comment by bjarthur** [comment]
PkgEval seems to be running again!  thanks to whoever fixed it.

**Comment by ararslan** [comment]
I don't think anyone actually touched it. It just happens to work or not work randomly...
