### ISSUE TITLE
Error in testing Diversity.jl on v0.6

### ISSUE THREAD

**Issue by richardreeve** [JuliaCI/PackageEvaluator.jl#195]
My package tests involve extensive cross-validation against R packages to demonstrate consistency of results. However this is fragile due to changes in R dependencies. I can maintain it so it continues to work using [travis](https://travis-ci.org/richardreeve/Diversity.jl/builds/330400342), but it's very hard with PackageEvaluator since I can't configure the latter. Ideally, I'd like to be able to test in my test script whether I'm being run by PackageEvaluator and just not do the cross-validation as I already know it works and it frequently makes my package look bad. Is there any way of doing this?

If not, can you install `libxml2-dev` as it do in my [.travis.yml](https://github.com/richardreeve/Diversity.jl/blob/master/.travis.yml) script, as that seems to be the current necessary fix and rerun PackageEvaluator on [Diversity.jl](https://github.com/richardreeve/Diversity.jl)?

**Comment by ararslan** [comment]
> Ideally, I'd like to be able to test in my test script whether I'm being run by PackageEvaluator and just not do the cross-validation as I already know it works and it frequently makes my package look bad. Is there any way of doing this?

#143, which seems unlikely to happen.

> If not, can you install libxml2-dev as it do in my .travis.yml script

That may be doable, I'll look into it.

**Comment by tkelman** [comment]
What do you need libxml2-dev for? There are other packages where it's actually useful to test that they work *without* having libxml2-dev present.

If you rely on a lot of hard-to-install dependencies that most users won't have installed, then is `Pkg.test` ever going to work for your users? You could move the messy extensive tests to be the ones that are behind an optional flag of your own and only run them locally and on your own CI.

**Comment by richardreeve** [comment]
My package has no non-Julia dependencies. I only need libxml2-dev for cross-validation against the matching R packages in the tests - there’s plenty of internal testing that checks everything I’m aware of being worth looking at, but I also generate a large number of random tests which I check against the corresponding R package for completeness. I don’t want to drop that, which is why I’d like to just ignore it PackageEvaluator is running and avoid all of this fuss.

**Comment by tkelman** [comment]
So you're doing cross-validation against R packages in Pkg.test? Packages really shouldn't behave differently if they're running in PackageEvaluator than they would if a user runs Pkg.test.

**Comment by ararslan** [comment]
One option would be to have those tests be opt-in rather than opt-out. For example, you could introduce an environment variable called e.g. `DIVERSITY_COMPARE_R` that you define on Travis but will not be defined on PackageEvaluator, and put the relevant tests behind an `if haskey(ENV, "DIVERSITY_COMPARE_R")`.

**Comment by richardreeve** [comment]
Sorry, maybe I’m misunderstanding you. I want travis to do the testing because I’m doing mine on a mac and I want to test it on linux as well as on my computer (and windows). Working on someone else’s computer is strictly secondary as far as I’m concerned. However, from that perspective I have it not do the cross-validation if R isn’t installed at all, but you install R, breaking my failsafe but then don’t install this package too :(

And from what I can tell from google, libxml2-dev is only necessary on some linux distributions - the R package has a workaround for libxml2-dev not being present, but it fails on ubuntu for some reason...

**Comment by richardreeve** [comment]
Ah, thanks @ararslan, that’s a good idea. I’ll see if I can do that.

**Comment by richardreeve** [comment]
Sorry - I’m on my phone and a bit behind on your messages. @tkelman - I understand that, that’s why I’d like libxml2-dev installed! Doing something different is just my backup plan.

**Comment by tkelman** [comment]
You could also add another check, if R is installed then ask whether these packages are installed. Last time I saw anyone attempt to install R packages in a scripted way it didn't work well at all.

Some of your users, who may want to run Pkg.test as a way of verifying whether the package is installed and working correctly (which is what pkgeval is simulating - someone else's computer), may happen to have R but not the extra R packages installed.

**Comment by richardreeve** [comment]
Yes, I tried that at one point, but then travis won’t run. I do install the packages successfully through julia though - I have to install to a private package repo rather than the default as that generates an interactive query about setting it up, but apart from that it seems okay.

**Comment by tkelman** [comment]
So the problem is that the installation fails if libxml2-dev is missing. If the installation fails, couldn't you move on and skip the extensive tests, proceeding as if R hadn't been there?

**Comment by richardreeve** [comment]
Hmm, most distributions and OSes don’t need the xml2 stuff, so that wouldn’t work, but maybe I can check if the igraph package successfully installed in R. I’ll see if I can work out how to do that. Probably not too hard. Thanks.

**Comment by richardreeve** [comment]
Okay, never mind - this is now fixed in the Diversity package in release [v0.4.2](https://github.com/JuliaLang/METADATA.jl/pull/13076).
