### ISSUE TITLE
Allow use to sort packages dynamically

### ISSUE THREAD

**Issue by goerz** [JuliaCI/PackageEvaluator.jl#197]
It would be nice if the list of packages at http://pkg.julialang.org could be dynamically sorted. The alphabetic listing only seems moderately useful. One thing I'd be particularly interested in is sorting by popularity (Github stars). Also age (most recent update) might be a good sorting option.

To take this one step further, it might also be good to be able to filter the list, e.g. by supported Julia version, by license, or by whether tests are passing.

**Comment by Nosferican** [comment]
I would prefer to have a nice API before injecting any javascript to the page...

**Comment by IainNZ** [comment]
The initial version of this did do this, using Angular, but saw limited usage and generally slowed down the page a lot/added complexity.
If you are willing to contribute this version yourself, please re-open and we discuss options.
