### ISSUE TITLE
Title for the package wrong?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaCI/PackageEvaluator.jl#208]
"A tool to evaluate the quality of Julia packages. http://pkg.julialang.org"

I'm not sure we should be pointing there as that list is frozen in the past. I guess it should point to: https://juliaobserver.com that includes new (and all old?) packages.

I'm just not sure how to change this (I guess only an admin, not a PR can do it).

**Comment by PallHaraldsson** [comment]
I now see "unmaintained" https://github.com/JuliaCI/PackageEvaluator.jl/issues/207

In case I'm not wrong, the link in the README and maybe elsewhere such as these following lines) should be changed:
https://github.com/JuliaCI/PackageEvaluator.jl/blob/3dbc8169e9d26aef36ceb97e3175465cebf2f2ec/website/build.sh#L24

**Comment by vchuravy** [comment]
This is the source code of the tooling that was used for pkg.julialang.org in the past. So I don't think there is anything to do here.
