### ISSUE TITLE
Evaluating packages on Windows?

### ISSUE THREAD

**Issue by tkelman** [JuliaCI/PackageEvaluator.jl#51]
Is this possible? How much work would need to be done to start doing this?

**Comment by tkelman** [comment]
Given that PkgEvaluator is now using Vagrant, this should be easier to do. Last I checked there are a couple of Windows images up on the Vagrant registry, or there are a few Packer recipes out there to build your own from an evaluation iso.

**Comment by IainNZ** [comment]
Absolutely. How does licensing work?

(note that the new [and old] PackageEvaluator(s) aren't currently operational, but I'm getting there with the new one.)

**Comment by tkelman** [comment]
IANAL...

@staticfloat what did you end up doing licensing-wise for the buildbots?

**Comment by staticfloat** [comment]
I believe I used some sort of volume licensing key that allowed me to install Windows on the MIT or UW campus networks.  I can't really remember which.

**Comment by IainNZ** [comment]
Closing due to age. Testing on other platforms would be nice, but there are enough issues with just one right now.
