### ISSUE TITLE
avoiding reporting errors caused by dependent packages

### ISSUE THREAD

**Issue by WestleyArgentum** [JuliaCI/PackageEvaluator.jl#64]
I haven't looked into this at all, but would it be possible to keep some state as you're testing packages - such that you knew whether dependencies had failed?

Lots of packages depend on ICU.jl, which is having trouble installing in the test environment. Because it fails to load, all the dependencies also report a failure, and issues are filed for them. It would be sweet if dependencies like ICU.jl were always evaluated first, and packages further down the line would only be tested if things before them worked.

Maybe there could even be some gravity added to the issue posted in the broken repo - "14 OTHER PACKAGES DEPEND ON THESE TESTS TO PASS" - or something

**Comment by IainNZ** [comment]
Closing due to age.
