### ISSUE TITLE
Expect.jl "untestable"

### ISSUE THREAD

**Issue by wavexx** [JuliaCI/PackageEvaluator.jl#90]
Hopefully I'm not at fault here:

http://pkg.julialang.org/?pkg=Expect&ver=release

I'm able to test the package using the regular Pkg.test(), but somehow it ended up excluded with eval_pkg without any test log. Is anything missing in the package?

**Comment by IainNZ** [comment]
For some reason it hangs Julia at the end of Pkg.test when run from PackageEvaluator, and can't be killed by `timeout`, so without the resources to debug it I just excluded it. If you can find a fix, I'd be happy to accept it. In a couple of months I'm planning to move to a simpler setup where it will probably work so I can also re-evaluate then.

**Comment by wavexx** [comment]
On 04/04/2015 11:13 PM, Iain Dunning wrote:
> For some reason it hangs Julia at the end of Pkg.test when run from
> PackageEvaluator, and can't be killed by `timeout`, so without the
> resources to debug it I just excluded it. If you can find a fix, I'd

That's actually interesting to know. I guess this explains why it took
so long to appear in the index.

Can I just run PackageEvaluator locally without vagrant, or do I need
the full setup to reproduce the issue?

**Comment by IainNZ** [comment]
The delay was me travelling, then me realizing that it was getting stuck at Expect added another couple of days :D

It can definitely run locally without Vagrant, hopefully the issue appears on your machine.

**Comment by wavexx** [comment]
Which version of Julia was hanging? I've just tested with 0.4 (master) and it works correctly :/
I tested by running:

    julia -e 'using PackageEvaluator; eval_pkg("Expect");'

and it dumped a correct 'Expect.json' on me.

**Comment by wavexx** [comment]
And 0.3.5 (from Debian) also worked fine...

**Comment by wavexx** [comment]
I updated Expect.jl to v0.1.1. Since I cannot reproduce the hang, could you let me know if you still have the issue?

**Comment by IainNZ** [comment]
I'll try reenabling it some time in the coming week

**Comment by wavexx** [comment]
Just in case, Expect.jl is not at 0.2, should fix the hanging issues in both Expect.jl and Polyglot.jl for Julia 0.5+.
